# -*- coding: utf-8 -*-
"""numpy practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AdHULnl0CVWAyflU5eP7WtP97-sWvf54
"""

import numpy as np
a=np.array([1,2])
print(a)
print(a.shape)



b=np.array([[1,2,3,4,], [7,8,9,10] ,[2,3,4,5]])
a=b[:3 ,1:4]
print(a)
print(type(a))

import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

print(a[0,2] ,a[1,2])
print(np.array([a[0,0],a[0,1]]))
print(a.ndim)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b=[0,1,2,0]
print(b)
print(a[:,b])
print(a[:2,b])